### ISSUE TITLE
Superseded by `cabal-plan`?

### ISSUE THREAD

**Issue by andreasabel** [jaspervdj/cabal-dependency-licenses#11]
This tool might be superseded by cabal-plan, see https://hackage.haskell.org/package/cabal-plan#description, which can produce a `license-report`.

If so, this information could maybe added to the README.

**Comment by jaspervdj** [comment]
Sounds good, yeah I don't really plan on maintaining this I don't have to.  I added a link to `cabal-plan`.  Thanks!
